# ############################################################################
# Model: Language model with a LSTM
# Training: JSB dataset
# Authors:  Edward Son 2021, Gabriel Kreplak 2021
# ############################################################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 2602
pickle: JSB Chorales
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/RNNLM/<pickle>/
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

data: !ref <pickle>.pickle
data_path: !ref data/<pickle>
midi_file: !ref <output_folder>/<pickle>.MIDI
resolution: 25
time_scale: 9
velocity: 80
note_duration: 15

train_csv: !ref <data_path>/train.csv
valid_csv: !ref <data_path>/valid.csv
test_csv: !ref <data_path>/test.csv

# The train logger writes training statistics to a file, as well as stdout.
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

# Training parameters
number_of_epochs: 2000
batch_size: 32
sequence_length: 100
lr: 0.001
dropout: 0.4
accu_steps: 2 # Gradient accumulation to simulate large batch training
ckpt_interval_minutes: 15 # save checkpoint every N min

# Dataloader options
train_dataloader_opts:
    batch_size: !ref <batch_size>
    shuffle: True

valid_dataloader_opts:
    batch_size: 1

test_dataloader_opts:
    batch_size: 1

# Model parameters
emb_dim: 88 # dimension of the embeddings
rnn_size: 200 # dimension of hidden layers
layers: 2 # number of hidden layers

# Outputs
output_neurons: 88 # index(blank/eos/bos) = 0

# LSTM custom model
model: !new:speechbrain.lobes.music_generation_models.custom_model.CustomModel
    embedding_dim: !ref <emb_dim>
    rnn_size: !ref <rnn_size>
    layers: !ref <layers>

# Cost function used for training the model
compute_cost: !name:speechbrain.nnet.losses.mse_loss # nll_loss

# This optimizer will be constructed by the Brain class after all parameters
# are moved to the correct device. Then it will be added to the checkpointer.
optimizer: !name:torch.optim.Adam
    lr: !ref <lr>

# This function manages learning rate annealing over the epochs.
# We here use the NewBoB algorithm, that anneals the learning rate if
# the improvements over two consecutive epochs is less than the defined
# threshold.
lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: 0.0003
    annealing_factor: 0.8
    patient: 500

# The first object passed to the Brain class is this "Epoch Counter"
# which is saved by the Checkpointer so that training can be resumed
# if it gets interrupted at any point.
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

# Objects in "modules" dict will have their parameters moved to the correct
# device, as well as having train()/eval() called on them by the Brain class.
modules:
    model: !ref <model>

# This object is used for saving the state of training both so that it
# can be resumed if it gets interrupted, and also so that the best checkpoint
# can be later loaded for evaluation or inference.
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        counter: !ref <epoch_counter>
